//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
// 
namespace SmartBugsClient.localhost {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSoap", Namespace="http://p16.pub.ro/")]
    public class WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public WebService() {
            this.Url = "http://localhost/SmartBugsServer/SmartBugsServer.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://p16.pub.ro/Hello", RequestNamespace="http://p16.pub.ro/", ResponseNamespace="http://p16.pub.ro/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Hello() {
            this.Invoke("Hello", new object[0]);
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginHello(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Hello", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public void EndHello(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
    }
}
